# Generated by Django 3.2 on 2023-05-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Zipcode',
            new_name='zipcode',
        ),
    ]
